### ISSUE TITLE
Sad

### ISSUE THREAD

**Issue by mohpor** [jessesquires/drumpf#2]
<img width="1338" alt="Screen Shot 2019-09-04 at 1 58 35 PM" src="https://user-images.githubusercontent.com/4954588/64243205-36fb8d00-cf1c-11e9-912a-43918c63b5a5.png">

MacOS Catalina.

**Comment by jessesquires** [comment]
Yes, very unfortunate 😞 

Apple has killed the old "standard" javascript browser extensions. 🤷‍♂
